### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0xSeanG**
adding some other podcasts in no particular order

### CODE REVIEW

**Comment by 0xSeanG** [comment]
adding andrewjkerr's list of cheatsheets

**Comment by 0xSeanG** [comment]
adding meetup.com

**Review by 0xbadshah — CHANGES_REQUESTED** [review]
Meetup.com is more general website and is not specific to security.

**Comment by gradiuscypher** [comment]
Thanks for the PR! Once the holidays have settled, I'll go through and review what's been submitted, and pull in items that are relevant to the project.

**Comment by 0xSeanG** [comment]
I didn't want to link to city specific groups, but in my city there are several city specific security meetups

**Comment by gradiuscypher** [comment]
@SDGoodwin - I've merged in the cheatsheet and podcasts, good resources :)

I've left the meetup link out as it's just a bit too generic.

Thanks for the contribution!

**Pull request merged**
